// Background Service Worker
// Generates design.md locally — no API key required
// Format based on 9-section DESIGN.md standard (Google Stitch)

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'generateDesignMd') {
    try {
      const markdown = buildDesignMd(message.data);
      sendResponse({ success: true, markdown });
    } catch (err) {
      sendResponse({ success: false, error: err.message });
    }
    return true;
  }
});

function buildDesignMd(d) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# DESIGN.md`);
  lines.push(`<!-- Generated by Design.md Extractor -->`);
  lines.push(`<!-- Source: ${d.url} -->`);
  lines.push(`<!-- Extracted: ${date} -->`);
  lines.push('');

  // ── 0. Technology Stack ─────────────────────────────────────────────────────
  lines.push('## Technology Stack');
  lines.push('');
  lines.push(`- JS Framework: ${d.meta?.framework || 'Unknown'}`);
  lines.push(`- CSS Approach: ${d.meta?.cssFramework || 'Unknown'}`);
  if (d.animations?.libraries?.length > 0) {
    lines.push(`- Animation Libraries: ${d.animations.libraries.join(', ')}`);
  }
  if (d.icons?.libraries?.length > 0) {
    lines.push(`- Icon Library: ${d.icons.libraries.join(', ')}`);
  }
  lines.push('');

  // ── 1. Visual Theme & Atmosphere ────────────────────────────────────────────
  lines.push('## Visual Theme & Atmosphere');
  lines.push('');
  const theme = d.theme || {};
  lines.push(theme.description || 'Unknown theme');
  lines.push('');
  if (theme.isMinimal) {
    lines.push('Emphasis on whitespace and typographic hierarchy. Minimal use of shadows.');
  }
  if (theme.hasGlass) {
    lines.push('Glassmorphism elements present — frosted glass panels with backdrop blur.');
  }
  if (theme.hasGradients) {
    lines.push('Gradient-forward design — backgrounds and/or CTAs use gradient fills.');
  }
  if (theme.isAnimated) {
    lines.push(`Motion-rich — transitions and animations are used heavily.`);
  }
  lines.push('');

  // ── 2. Color Palette & Roles ────────────────────────────────────────────────
  lines.push('## Color Palette & Roles');
  lines.push('');

  const roles = d.colorRoles || {};
  const vars = d.cssVariables || {};

  // CSS Variables — highest fidelity source
  const hasVars = Object.keys(vars).length > 0;
  if (hasVars) {
    lines.push('### CSS Variables (Design Tokens)');
    lines.push('```css');
    lines.push(':root {');
    Object.entries(vars).slice(0, 60).forEach(([k, v]) => lines.push(`  ${k}: ${v};`));
    lines.push('}');
    lines.push('```');
    lines.push('');
  }

  // Semantic roles from CSS variable names
  if (roles.accents?.length > 0) {
    lines.push('### Brand / Accent');
    roles.accents.slice(0, 5).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    lines.push('');
  }
  if (roles.semantic && Object.keys(roles.semantic).length > 0) {
    lines.push('### Semantic');
    Object.entries(roles.semantic).forEach(([role, val]) => {
      if (val) lines.push(`- ${capitalize(role)}: \`${val}\``);
    });
    lines.push('');
  }
  if (roles.backgrounds?.length > 0) {
    lines.push('### Surface');
    roles.backgrounds.slice(0, 4).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    if (roles.surfaces?.length > 0) {
      roles.surfaces.slice(0, 2).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    }
    if (roles.borders?.length > 0) {
      roles.borders.slice(0, 2).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    }
    lines.push('');
  }
  if (roles.text?.length > 0) {
    lines.push('### Text');
    roles.text.slice(0, 4).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    lines.push('');
  }

  // Brand/Accent colors — shown prominently even if low frequency
  if (roles.accents?.length > 0) {
    lines.push('### Brand / Accent');
    roles.accents.slice(0, 6).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    lines.push('');
  }

  // Top colors by frequency (raw data)
  if (d.colors?.length > 0) {
    lines.push('### All Colors by Frequency');
    lines.push('');
    lines.push('| Hex | Count | Role |');
    lines.push('|-----|-------|------|');
    const accentSet = new Set((roles.accents || []).map(a => a.value.toUpperCase()));
    const bgSet = new Set((roles.backgrounds || []).map(b => b.value.toUpperCase()));
    const textSet = new Set((roles.text || []).map(t => t.value.toUpperCase()));
    d.colors.slice(0, 16).forEach(({ color, count }) => {
      let role = '';
      if (accentSet.has(color)) role = 'accent';
      else if (bgSet.has(color)) role = 'bg';
      else if (textSet.has(color)) role = 'text';
      lines.push(`| \`${color}\` | ${count} | ${role} |`);
    });
    lines.push('');
  }

  // ── 3. Gradients ────────────────────────────────────────────────────────────
  const grads = d.gradients || {};
  const hasGrads = (grads.backgrounds?.length || grads.buttons?.length || grads.text?.length || grads.glassmorphism?.length);
  if (hasGrads) {
    lines.push('## Gradients');
    lines.push('');
    if (grads.backgrounds?.length > 0) {
      lines.push('### Background Gradients');
      lines.push('```css');
      grads.backgrounds.forEach((g, i) => lines.push(`/* bg-gradient-${i+1} */ background-image: ${g};`));
      lines.push('```');
      lines.push('');
    }
    if (grads.buttons?.length > 0) {
      lines.push('### Button / CTA Gradients');
      lines.push('```css');
      grads.buttons.forEach((g, i) => lines.push(`/* btn-gradient-${i+1} */ background-image: ${g};`));
      lines.push('```');
      lines.push('');
    }
    if (grads.text?.length > 0) {
      lines.push('### Text Gradients');
      lines.push('```css');
      grads.text.forEach((g, i) => {
        lines.push(`/* text-gradient-${i+1} */`);
        lines.push(`background-image: ${g};`);
        lines.push(`-webkit-background-clip: text;`);
        lines.push(`-webkit-text-fill-color: transparent;`);
      });
      lines.push('```');
      lines.push('');
    }
    if (grads.glassmorphism?.length > 0) {
      lines.push('### Glassmorphism');
      lines.push('```css');
      grads.glassmorphism.forEach((g, i) => {
        lines.push(`/* glass-${i+1} */`);
        lines.push(`backdrop-filter: ${g.backdropFilter};`);
        if (g.background) lines.push(`background: ${g.background};`);
        if (g.border)     lines.push(`border-color: ${g.border};`);
      });
      lines.push('```');
      lines.push('');
    }
  }

  // ── 4. Typography Rules ─────────────────────────────────────────────────────
  lines.push('## Typography Rules');
  lines.push('');

  const typo = d.typography || {};
  const fonts = d.fonts || {};

  // Font families
  if (fonts.detected?.length > 0 || fonts.mono?.length > 0) {
    lines.push('### Font Families');
    if (fonts.detected?.length > 0) lines.push(`- Primary (UI): ${fonts.detected[0]}`);
    if (fonts.detected?.length > 1) lines.push(`- Secondary (Display): ${fonts.detected[1]}`);
    if (fonts.mono?.length > 0)     lines.push(`- Monospace (Code): ${fonts.mono[0]}`);
    if (fonts.googleFontsUrls?.length > 0) {
      lines.push(`- Font loading: Google Fonts`);
      fonts.googleFontsUrls.forEach(u => lines.push(`  ${u}`));
    }
    lines.push('');
  }

  // Fluid typography note
  if (typo._isFluid) {
    lines.push('> **Note:** This site uses fluid/responsive typography (vw, clamp, or viewport-relative units).');
    lines.push('> Pixel values below are computed at the current viewport. Actual values will vary by screen size.');
    lines.push('');
  }

  // Type scale
  const typoEntries = Object.entries(typo).filter(([k]) => !k.startsWith('_'));
  if (typoEntries.length > 0) {
    lines.push('### Type Scale');
    lines.push('');
    lines.push('| Element | Size | Weight | Line height | Letter spacing |');
    lines.push('|---------|------|--------|-------------|----------------|');
    typoEntries.forEach(([tag, s]) => {
      lines.push(`| \`${tag}\` | ${s.fontSize} | ${s.fontWeight} | ${s.lineHeight} | ${s.letterSpacing || '—'} |`);
    });
    lines.push('');

    // Letter spacing for special cases
    const h1 = typo.h1;
    if (h1?.letterSpacing && h1.letterSpacing !== 'normal' && h1.letterSpacing !== '0px') {
      lines.push('### Letter Spacing');
      lines.push(`- Headings: ${h1.letterSpacing}`);
      if (typo.button?.letterSpacing && typo.button.letterSpacing !== 'normal') {
        lines.push(`- Labels/Buttons: ${typo.button.letterSpacing}`);
      }
      lines.push('');
    }
  }

  // ── 5. Spacing & Layout ─────────────────────────────────────────────────────
  lines.push('## Spacing & Layout');
  lines.push('');

  const spacing = d.spacing || {};
  const baseUnit = spacing.baseUnit || '8px';
  lines.push(`Base unit: ${baseUnit}`);
  lines.push('');

  if (spacing.values?.length > 0) {
    lines.push('### Scale');
    const vals = spacing.values.filter(v => v.endsWith('px')).slice(0, 12);
    const namedScale = buildSpacingScale(vals, baseUnit);
    namedScale.forEach(({ name, value }) => lines.push(`- ${name}: ${value}`));
    lines.push('');
  }

  if (d.breakpoints?.length > 0) {
    lines.push('### Breakpoints');
    const bps = d.breakpoints;
    lines.push(`- Mobile: < ${bps[0] || '640px'}`);
    if (bps.length > 1) lines.push(`- Tablet: ${bps[0]} – ${bps[Math.floor(bps.length/2)] || '1024px'}`);
    lines.push(`- Desktop: > ${bps[Math.floor(bps.length/2)] || '1024px'}`);
    if (bps.length > 2) lines.push(`- Wide: > ${bps[bps.length-1]}`);
    lines.push('');
    lines.push('All breakpoints: ' + bps.join(' · '));
    lines.push('');
  }

  // ── 6. Component Stylings ───────────────────────────────────────────────────
  lines.push('## Component Stylings');
  lines.push('');

  const comp = d.components || {};

  if (comp.button) {
    const s = comp.button.sample;
    lines.push('### Buttons');
    lines.push('');
    lines.push('**Primary**');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    lines.push(`- Text: \`${s.color}\``);
    if (s.border && s.border !== 'none') lines.push(`- Border: \`${s.border}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    lines.push(`- Font: ${s.fontSize} / ${s.fontWeight}`);
    if (s.letterSpacing && s.letterSpacing !== 'normal') lines.push(`- Letter spacing: ${s.letterSpacing}`);
    if (s.textTransform && s.textTransform !== 'none') lines.push(`- Text transform: ${s.textTransform}`);
    if (s.transition) lines.push(`- Transition: \`${s.transition}\``);
    lines.push(`- Count on page: ${comp.button.count}`);
    lines.push('');
  }

  if (comp.card) {
    const s = comp.card.sample;
    lines.push('### Cards');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    if (s.border && s.border !== 'none') lines.push(`- Border: \`${s.border}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    if (s.boxShadow) lines.push(`- Shadow: \`${s.boxShadow}\``);
    if (s.transition) lines.push(`- Hover transition: \`${s.transition}\``);
    lines.push('');
  }

  if (comp.input) {
    const s = comp.input.sample;
    lines.push('### Inputs / Form Fields');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    lines.push(`- Border: \`${s.border}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    lines.push(`- Font size: ${s.fontSize}`);
    lines.push(`- Text color: \`${s.color}\``);
    lines.push('');
  }

  if (comp.navigation) {
    const s = comp.navigation;
    lines.push('### Navigation / Header');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    if (s.height) lines.push(`- Height: ${s.height}`);
    if (s.borderBottom && s.borderBottom !== 'none') lines.push(`- Border bottom: \`${s.borderBottom}\``);
    if (s.backdropFilter) lines.push(`- Backdrop filter: \`${s.backdropFilter}\``);
    lines.push('');
  }

  if (comp.badge) {
    const s = comp.badge.sample;
    lines.push('### Badges / Tags / Pills');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    lines.push(`- Text: \`${s.color}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    lines.push(`- Font size: ${s.fontSize}`);
    lines.push('');
  }

  // ── 7. Border Radius & Shadows ──────────────────────────────────────────────
  if (d.borderRadius?.length > 0 || d.shadows?.length > 0) {
    lines.push('## Border Radius & Shadows');
    lines.push('');

    if (d.borderRadius?.length > 0) {
      lines.push('### Border Radius Scale');
      lines.push(d.borderRadius.join(' · '));
      lines.push('');
    }

    if (d.shadows?.length > 0) {
      lines.push('### Shadows & Elevation');
      lines.push('```css');
      d.shadows.slice(0, 8).forEach((s, i) => lines.push(`/* shadow-${i+1} */ box-shadow: ${s};`));
      lines.push('```');
      lines.push('');
    }
  }

  // ── 8. Animations & Motion ──────────────────────────────────────────────────
  const anim = d.animations || {};
  const hasAnim = anim.transitions?.length || anim.animations?.length || anim.keyframes?.length || anim.libraries?.length;
  if (hasAnim) {
    lines.push('## Animations & Motion');
    lines.push('');

    if (anim.libraries?.length > 0) {
      lines.push('### Animation Technologies Detected');
      anim.libraries.forEach(lib => lines.push(`- ${lib}`));
      lines.push('');
    }

    if (anim.transitions?.length > 0) {
      lines.push('### Transition Patterns');
      lines.push('```css');
      anim.transitions.slice(0, 6).forEach((t, i) => lines.push(`/* transition-${i+1} */ transition: ${t};`));
      lines.push('```');
      lines.push('');
    }

    if (anim.animations?.length > 0) {
      lines.push('### Active Animations (CSS)');
      lines.push('```css');
      anim.animations.slice(0, 4).forEach((a, i) => lines.push(`/* animation-${i+1} */ animation: ${a};`));
      lines.push('```');
      lines.push('');
    }

    if (anim.keyframes?.length > 0) {
      lines.push('### Keyframe Names Detected');
      lines.push(anim.keyframes.join(', '));
      lines.push('');
    }

    // Extract default duration and easing from first transition
    if (anim.transitions?.length > 0) {
      const first = anim.transitions[0];
      const durationMatch = first.match(/(\d+\.?\d*m?s)/);
      const easingMatch = first.match(/(ease[-\w]*|linear|cubic-bezier[^,)]+\))/);
      if (durationMatch || easingMatch) {
        lines.push('### Motion Principles');
        if (durationMatch) lines.push(`- Default duration: ${durationMatch[1]}`);
        if (easingMatch)   lines.push(`- Default easing: ${easingMatch[1]}`);
        lines.push(`- Reduced motion: Use \`@media (prefers-reduced-motion: reduce)\` to disable animations`);
        lines.push('');
      }
    }
  }

  // ── Decorative details ──────────────────────────────────────────────────────
  const deco = d.decorative || {};
  const scrollbar = deco.scrollbar || {};
  const hasScrollbar = scrollbar.width || scrollbar.thumbColor;
  const hasSelection = deco.selection;

  if (hasScrollbar || hasSelection) {
    lines.push('## Decorative Details');
    lines.push('');

    if (hasScrollbar) {
      lines.push('### Custom Scrollbar');
      lines.push('```css');
      if (scrollbar.width)       lines.push(`::-webkit-scrollbar { width: ${scrollbar.width}; }`);
      if (scrollbar.trackColor)  lines.push(`::-webkit-scrollbar-track { background: ${scrollbar.trackColor}; }`);
      if (scrollbar.thumbColor)  lines.push(`::-webkit-scrollbar-thumb { background: ${scrollbar.thumbColor}; border-radius: ${scrollbar.thumbRadius || '4px'}; }`);
      lines.push('```');
      lines.push('');
    }

    if (hasSelection) {
      lines.push('### Selection Color');
      lines.push('```css');
      lines.push(`::selection {`);
      if (deco.selection.background) lines.push(`  background: ${deco.selection.background};`);
      if (deco.selection.color)      lines.push(`  color: ${deco.selection.color};`);
      lines.push(`}`);
      lines.push('```');
      lines.push('');
    }
  }

  // ── Z-Index Scale ────────────────────────────────────────────────────────────
  if (d.zIndex?.length > 0) {
    lines.push('## Z-Index Scale');
    lines.push('');
    lines.push('Detected values: ' + d.zIndex.join(' · '));
    lines.push('');
  }

  // ── Icon System ─────────────────────────────────────────────────────────────
  if (d.icons?.libraries?.length > 0) {
    lines.push('## Icon System');
    lines.push('');
    lines.push(`- Library: ${d.icons.libraries.join(', ')}`);
    if (d.icons.defaultSize) lines.push(`- Default size: ${d.icons.defaultSize}`);
    lines.push('');
  }

  // ── 9. Do's and Don'ts ──────────────────────────────────────────────────────
  lines.push('## Do\'s and Don\'ts');
  lines.push('');
  lines.push('### DO');

  const dos = buildDos(d);
  dos.forEach(item => lines.push(`- ${item}`));
  lines.push('');
  lines.push("### DON'T");

  const donts = buildDonts(d);
  donts.forEach(item => lines.push(`- ${item}`));
  lines.push('');

  // ── Responsive Behavior ──────────────────────────────────────────────────────
  if (d.breakpoints?.length > 0) {
    lines.push('## Responsive Behavior');
    lines.push('');
    const bps = d.breakpoints;
    lines.push(`- Mobile (< ${bps[0]}): single column layout, full-width CTAs`);
    if (bps.length > 1) lines.push(`- Tablet (${bps[0]} – ${bps[Math.floor(bps.length/2)]}): 2-column max`);
    lines.push(`- Desktop (> ${bps[Math.floor(bps.length/2)] || '1024px'}): multi-column, full navigation`);
    lines.push('');
  }

  // ── Agent Prompt Guide ───────────────────────────────────────────────────────
  lines.push('## Agent Prompt Guide');
  lines.push('');
  lines.push('Always reference this file before generating or modifying any UI component.');
  lines.push('');
  lines.push('- Use **only** colors from "Color Palette & Roles" — never invent values');
  if (d.fonts?.detected?.length > 0) {
    lines.push(`- Use **only** ${d.fonts.detected[0]} font family — never substitute`);
  }
  lines.push('- Apply spacing from the defined scale — maintain the base grid unit');
  lines.push('- Match all component states: hover, focus, active, disabled');
  if (d.animations?.transitions?.length > 0) {
    lines.push('- Replicate transition patterns — match duration and easing');
  }
  if (d.icons?.libraries?.length > 0) {
    lines.push(`- Use ${d.icons.libraries[0]} icon library at consistent sizes`);
  }
  lines.push('- Respect `prefers-reduced-motion` for all animations');
  lines.push('- When in doubt about any value not listed — ask, do not guess');

  return lines.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function buildSpacingScale(pxValues, baseUnit) {
  const base = parseInt(baseUnit) || 8;
  const names = ['xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', '4xl'];
  // Deduplicate and sort
  const unique = [...new Set(pxValues.map(v => parseFloat(v)))].sort((a, b) => a - b);
  return unique.slice(0, 8).map((val, i) => ({
    name: names[i] || `${i+1}x`,
    value: `${val}px`
  }));
}

function buildDos(d) {
  const dos = [];
  const comp = d.components || {};
  const theme = d.theme || {};

  if (comp.card?.sample?.border && !comp.card.sample.boxShadow) {
    dos.push('Use 1px borders on cards (no drop shadows)');
  } else if (comp.card?.sample?.boxShadow) {
    dos.push('Use box shadows for card elevation');
  }
  if (d.fonts?.detected?.length > 0) {
    dos.push(`Use ${d.fonts.detected[0]} for all UI text`);
  }
  if (d.spacing?.baseUnit) {
    dos.push(`Maintain ${d.spacing.baseUnit} grid alignment`);
  }
  if (d.animations?.transitions?.length > 0) {
    dos.push('Apply smooth transitions on interactive elements');
  }
  if (theme.isDark) {
    dos.push('Keep the dark background — do not switch to white surfaces');
  }
  if (d.borderRadius?.length > 0) {
    dos.push(`Use border-radius values from the defined scale (${d.borderRadius.slice(0,3).join(', ')})`);
  }
  dos.push('Use semantic color names from the token system');
  dos.push('Match hover/focus states to existing component patterns');
  return dos;
}

function buildDonts(d) {
  const donts = [];
  const theme = d.theme || {};
  const comp = d.components || {};

  donts.push('Never use colors outside the defined palette');
  if (d.fonts?.detected?.length > 0) {
    donts.push(`Never substitute ${d.fonts.detected[0]} with system fonts`);
  }
  if (theme.isMinimal && d.shadows?.length < 3) {
    donts.push('Don\'t add heavy drop shadows — this is a minimal/flat design');
  }
  donts.push('Don\'t use font sizes outside the defined type scale');
  donts.push('Don\'t use arbitrary z-index values — stick to the z-index scale');
  if (!theme.hasGradients) {
    donts.push('Don\'t add gradient fills — the design uses flat colors');
  }
  donts.push('Don\'t disable focus styles — they\'re required for accessibility');
  return donts;
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
