// Background Service Worker
// Generates design.md locally — no API key required
// Format based on 9-section DESIGN.md standard (Google Stitch)

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'generateDesignMd') {
    try {
      const markdown = buildDesignMd(message.data);
      sendResponse({ success: true, markdown });
    } catch (err) {
      sendResponse({ success: false, error: err.message });
    }
    return true;
  }
});

function buildDesignMd(d) {
  const lines = [];
  const date = new Date().toISOString().slice(0, 10);

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# DESIGN.md`);
  lines.push(`<!-- Generated by Design.md Extractor -->`);
  lines.push(`<!-- Source: ${d.url} -->`);
  lines.push(`<!-- Extracted: ${date} -->`);
  lines.push('');

  // ── 0. Technology Stack ─────────────────────────────────────────────────────
  lines.push('## Technology Stack');
  lines.push('');
  lines.push(`- JS Framework: ${d.meta?.framework || 'Unknown'}`);
  lines.push(`- CSS Approach: ${d.meta?.cssFramework || 'Unknown'}`);
  if (d.animations?.libraries?.length > 0) {
    lines.push(`- Animation Libraries: ${d.animations.libraries.join(', ')}`);
  }
  if (d.icons?.libraries?.length > 0) {
    lines.push(`- Icon Library: ${d.icons.libraries.join(', ')}`);
  }
  lines.push('');

  // ── 1. Visual Theme & Atmosphere ────────────────────────────────────────────
  lines.push('## Visual Theme & Atmosphere');
  lines.push('');
  const theme = d.theme || {};
  lines.push(theme.description || 'Unknown theme');
  lines.push('');
  if (theme.isMinimal) {
    lines.push('Emphasis on whitespace and typographic hierarchy. Minimal use of shadows.');
  }
  if (theme.hasGlass) {
    lines.push('Glassmorphism elements present — frosted glass panels with backdrop blur.');
  }
  if (theme.hasGradients) {
    lines.push('Gradient-forward design — backgrounds and/or CTAs use gradient fills.');
  }
  if (theme.isAnimated) {
    lines.push(`Motion-rich — transitions and animations are used heavily.`);
  }
  lines.push('');

  // ── 2. Color Palette & Roles ────────────────────────────────────────────────
  lines.push('## Color Palette & Roles');
  lines.push('');

  const roles = d.colorRoles || {};
  const vars = d.cssVariables || {};

  // CSS Variables — highest fidelity source
  const hasVars = Object.keys(vars).length > 0;
  if (hasVars) {
    lines.push('### CSS Variables (Design Tokens)');
    lines.push('```css');
    lines.push(':root {');
    Object.entries(vars).slice(0, 60).forEach(([k, v]) => lines.push(`  ${k}: ${v};`));
    lines.push('}');
    lines.push('```');
    lines.push('');
  }

  // Semantic roles from CSS variable names
  if (roles.accents?.length > 0) {
    lines.push('### Brand / Accent');
    roles.accents.slice(0, 5).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    lines.push('');
  }
  if (roles.semantic && Object.keys(roles.semantic).length > 0) {
    lines.push('### Semantic');
    Object.entries(roles.semantic).forEach(([role, val]) => {
      if (val) lines.push(`- ${capitalize(role)}: \`${val}\``);
    });
    lines.push('');
  }
  if (roles.backgrounds?.length > 0) {
    lines.push('### Surface');
    roles.backgrounds.slice(0, 4).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    if (roles.surfaces?.length > 0) {
      roles.surfaces.slice(0, 2).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    }
    if (roles.borders?.length > 0) {
      roles.borders.slice(0, 2).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    }
    lines.push('');
  }
  if (roles.text?.length > 0) {
    lines.push('### Text');
    roles.text.slice(0, 4).forEach(({ name, value }) => lines.push(`- ${name}: \`${value}\``));
    lines.push('');
  }

  // Top colors by frequency (raw data)
  if (d.colors?.length > 0) {
    lines.push('### All Colors by Frequency');
    lines.push('');
    lines.push('| Hex | Count | Role |');
    lines.push('|-----|-------|------|');
    const accentSet = new Set((roles.accents || []).map(a => a.value.toUpperCase()));
    const bgSet = new Set((roles.backgrounds || []).map(b => b.value.toUpperCase()));
    const textSet = new Set((roles.text || []).map(t => t.value.toUpperCase()));
    d.colors.slice(0, 16).forEach(({ color, count }) => {
      let role = '';
      if (accentSet.has(color)) role = 'accent';
      else if (bgSet.has(color)) role = 'bg';
      else if (textSet.has(color)) role = 'text';
      lines.push(`| \`${color}\` | ${count} | ${role} |`);
    });
    lines.push('');
  }

  // ── Color Usage Rules ───────────────────────────────────────────────────────
  {
    const pairs = buildColorPairs(d);
    const colorRules = buildColorRules(d);

    if (pairs.length > 0 || colorRules.length > 0) {
      lines.push('### Color Usage Rules');
      lines.push('');

      if (pairs.length > 0) {
        lines.push('**Valid text/background combinations (WCAG contrast):**');
        lines.push('');
        lines.push('| Background | Text | Contrast | Rating |');
        lines.push('|-----------|------|----------|--------|');
        pairs.forEach(({ bg, text, ratio, rating }) => {
          lines.push(`| \`${bg}\` | \`${text}\` | ${ratio}:1 | ${rating} |`);
        });
        lines.push('');
      }

      if (colorRules.length > 0) {
        colorRules.forEach(rule => lines.push(`- ${rule}`));
        lines.push('');
      }
    }
  }

  // ── 3. Gradients ────────────────────────────────────────────────────────────
  const grads = d.gradients || {};
  const hasGrads = (grads.backgrounds?.length || grads.buttons?.length || grads.text?.length || grads.glassmorphism?.length);
  if (hasGrads) {
    lines.push('## Gradients');
    lines.push('');
    if (grads.backgrounds?.length > 0) {
      lines.push('### Background Gradients');
      lines.push('```css');
      grads.backgrounds.forEach((g, i) => lines.push(`/* bg-gradient-${i+1} */ background-image: ${g};`));
      lines.push('```');
      lines.push('');
    }
    if (grads.buttons?.length > 0) {
      lines.push('### Button / CTA Gradients');
      lines.push('```css');
      grads.buttons.forEach((g, i) => lines.push(`/* btn-gradient-${i+1} */ background-image: ${g};`));
      lines.push('```');
      lines.push('');
    }
    if (grads.text?.length > 0) {
      lines.push('### Text Gradients');
      lines.push('```css');
      grads.text.forEach((g, i) => {
        lines.push(`/* text-gradient-${i+1} */`);
        lines.push(`background-image: ${g};`);
        lines.push(`-webkit-background-clip: text;`);
        lines.push(`-webkit-text-fill-color: transparent;`);
      });
      lines.push('```');
      lines.push('');
    }
    if (grads.glassmorphism?.length > 0) {
      lines.push('### Glassmorphism');
      lines.push('```css');
      grads.glassmorphism.forEach((g, i) => {
        lines.push(`/* glass-${i+1} */`);
        lines.push(`backdrop-filter: ${g.backdropFilter};`);
        if (g.background) lines.push(`background: ${g.background};`);
        if (g.border)     lines.push(`border-color: ${g.border};`);
      });
      lines.push('```');
      lines.push('');
    }
  }

  // ── 4. Typography Rules ─────────────────────────────────────────────────────
  lines.push('## Typography Rules');
  lines.push('');

  const typo = d.typography || {};
  const fonts = d.fonts || {};

  // Font families — full stacks from computed typography data
  {
    const fontRoles = [];
    const seenPrimary = new Set();

    const roleMap = [
      { selectors: ['h1', 'h2', 'h3'], role: 'Display / Heading' },
      { selectors: ['p', 'a', 'small'], role: 'Body' },
      { selectors: ['button', 'label'], role: 'UI / Button' },
      { selectors: ['code'], role: 'Monospace / Code' }
    ];

    roleMap.forEach(({ selectors, role }) => {
      for (const sel of selectors) {
        const t = typo[sel];
        if (!t?.fontFamily) continue;
        const primary = t.fontFamily.split(',')[0].replace(/['"]/g, '').trim();
        if (!primary || seenPrimary.has(primary)) break;
        seenPrimary.add(primary);
        fontRoles.push({ role, primary, full: t.fontFamily, featureSettings: t.fontFeatureSettings });
        break;
      }
    });

    // Fallback to fonts.detected if typography didn't yield results
    if (fontRoles.length === 0 && fonts.detected?.length > 0) {
      if (fonts.detected[0]) fontRoles.push({ role: 'Primary (UI)', primary: fonts.detected[0], full: fonts.detected[0] });
      if (fonts.detected[1]) fontRoles.push({ role: 'Secondary (Display)', primary: fonts.detected[1], full: fonts.detected[1] });
    }
    if (fonts.mono?.length > 0 && !fontRoles.find(r => r.role === 'Monospace / Code')) {
      fontRoles.push({ role: 'Monospace / Code', primary: fonts.mono[0], full: fonts.mono[0] });
    }

    if (fontRoles.length > 0) {
      lines.push('### Font Families');
      lines.push('');
      fontRoles.forEach(({ role, primary, full }) => {
        lines.push(`- **${role}**: \`${primary}\``);
        if (full && full !== primary) {
          lines.push(`  - Fallbacks: \`${full}\``);
        }
      });
      if (fonts.googleFontsUrls?.length > 0) {
        lines.push(`- Font loading: Google Fonts`);
      }
      lines.push('');

      // OpenType features
      const otFeatures = fontRoles.filter(r => r.featureSettings);
      if (otFeatures.length > 0) {
        lines.push('### OpenType Features');
        otFeatures.forEach(({ role, primary, featureSettings }) => {
          lines.push(`- \`${primary}\` (${role}): \`font-feature-settings: ${featureSettings}\``);
        });
        lines.push('');
      }
    }
  }

  // Fluid typography note
  if (typo._isFluid) {
    lines.push('> **Note:** This site uses fluid/responsive typography (vw, clamp, or viewport-relative units).');
    lines.push('> Pixel values below are computed at the current viewport. Actual values will vary by screen size.');
    lines.push('');
  }

  // Type scale
  const typoEntries = Object.entries(typo).filter(([k]) => !k.startsWith('_'));
  if (typoEntries.length > 0) {
    lines.push('### Type Scale');
    lines.push('');
    lines.push('| Element | Size | Weight | Line height | Letter spacing |');
    lines.push('|---------|------|--------|-------------|----------------|');
    typoEntries.forEach(([tag, s]) => {
      lines.push(`| \`${tag}\` | ${s.fontSize} | ${s.fontWeight} | ${s.lineHeight} | ${s.letterSpacing || '—'} |`);
    });
    lines.push('');

    // Letter spacing for special cases
    const h1 = typo.h1;
    if (h1?.letterSpacing && h1.letterSpacing !== 'normal' && h1.letterSpacing !== '0px') {
      lines.push('### Letter Spacing');
      lines.push(`- Headings: ${h1.letterSpacing}`);
      if (typo.button?.letterSpacing && typo.button.letterSpacing !== 'normal') {
        lines.push(`- Labels/Buttons: ${typo.button.letterSpacing}`);
      }
      lines.push('');
    }
  }

  // ── 5. Spacing & Layout ─────────────────────────────────────────────────────
  lines.push('## Spacing & Layout');
  lines.push('');

  const spacing = d.spacing || {};
  const baseUnit = spacing.baseUnit || '8px';
  lines.push(`Base unit: ${baseUnit}`);
  lines.push('');

  if (spacing.values?.length > 0) {
    lines.push('### Scale');
    const vals = spacing.values.filter(v => v.endsWith('px')).slice(0, 12);
    const namedScale = buildSpacingScale(vals, baseUnit);
    namedScale.forEach(({ name, value }) => lines.push(`- ${name}: ${value}`));
    lines.push('');
  }

  if (d.breakpoints?.length > 0) {
    lines.push('### Breakpoints');
    const bps = d.breakpoints;
    lines.push(`- Mobile: < ${bps[0] || '640px'}`);
    if (bps.length > 1) lines.push(`- Tablet: ${bps[0]} – ${bps[Math.floor(bps.length/2)] || '1024px'}`);
    lines.push(`- Desktop: > ${bps[Math.floor(bps.length/2)] || '1024px'}`);
    if (bps.length > 2) lines.push(`- Wide: > ${bps[bps.length-1]}`);
    lines.push('');
    lines.push('All breakpoints: ' + bps.join(' · '));
    lines.push('');
  }

  // ── 6. Component Stylings ───────────────────────────────────────────────────
  lines.push('## Component Stylings');
  lines.push('');

  const comp = d.components || {};

  // Button variants — use new multi-variant data if available, fallback to single
  const btnVariants = d.buttonVariants?.length > 0 ? d.buttonVariants : (comp.button ? [{ type: 'primary', ...comp.button.sample }] : []);
  if (btnVariants.length > 0) {
    lines.push('### Buttons');
    lines.push('');
    btnVariants.forEach(s => {
      const label = s.type ? s.type.charAt(0).toUpperCase() + s.type.slice(1) : 'Primary';
      lines.push(`**${label}**`);
      lines.push(`- Background: \`${s.backgroundColor}\``);
      lines.push(`- Text: \`${s.color}\``);
      if (s.border && s.border !== 'none') lines.push(`- Border: \`${s.border}\``);
      lines.push(`- Border radius: \`${s.borderRadius}\``);
      lines.push(`- Padding: \`${s.padding}\``);
      lines.push(`- Font: ${s.fontSize} / ${s.fontWeight}`);
      if (s.letterSpacing) lines.push(`- Letter spacing: ${s.letterSpacing}`);
      if (s.textTransform) lines.push(`- Text transform: ${s.textTransform}`);
      if (s.boxShadow) lines.push(`- Shadow: \`${s.boxShadow}\``);
      if (s.transition) lines.push(`- Transition: \`${s.transition}\``);
      lines.push('');
    });
    if (comp.button?.count) lines.push(`> ${comp.button.count} button elements detected on page\n`);
  }

  if (comp.card) {
    const s = comp.card.sample;
    lines.push('### Cards');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    if (s.border && s.border !== 'none') lines.push(`- Border: \`${s.border}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    if (s.boxShadow) lines.push(`- Shadow: \`${s.boxShadow}\``);
    if (s.transition) lines.push(`- Hover transition: \`${s.transition}\``);
    lines.push('');
  }

  if (comp.input) {
    const s = comp.input.sample;
    lines.push('### Inputs / Form Fields');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    lines.push(`- Border: \`${s.border}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    lines.push(`- Font size: ${s.fontSize}`);
    lines.push(`- Text color: \`${s.color}\``);
    lines.push('');
  }

  if (comp.navigation) {
    const s = comp.navigation;
    lines.push('### Navigation / Header');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    if (s.height) lines.push(`- Height: ${s.height}`);
    if (s.borderBottom && s.borderBottom !== 'none') lines.push(`- Border bottom: \`${s.borderBottom}\``);
    if (s.backdropFilter) lines.push(`- Backdrop filter: \`${s.backdropFilter}\``);
    lines.push('');
  }

  if (comp.badge) {
    const s = comp.badge.sample;
    lines.push('### Badges / Tags / Pills');
    lines.push(`- Background: \`${s.backgroundColor}\``);
    lines.push(`- Text: \`${s.color}\``);
    lines.push(`- Border radius: \`${s.borderRadius}\``);
    lines.push(`- Padding: \`${s.padding}\``);
    lines.push(`- Font size: ${s.fontSize}`);
    lines.push('');
  }

  // ── 7. Border Radius & Shadows ──────────────────────────────────────────────
  if (d.borderRadius?.length > 0 || d.shadows?.length > 0) {
    lines.push('## Border Radius & Shadows');
    lines.push('');

    if (d.borderRadius?.length > 0) {
      lines.push('### Border Radius Scale');
      lines.push(d.borderRadius.join(' · '));
      lines.push('');
    }

    if (d.shadows?.length > 0) {
      lines.push('### Shadows & Elevation');
      lines.push('');
      lines.push('| Level | Shadow |');
      lines.push('|-------|--------|');
      const shadowLabels = ['Subtle (cards)', 'Standard (floating)', 'Elevated (modals)', 'Focus ring'];
      d.shadows.slice(0, 6).forEach((s, i) => {
        const label = shadowLabels[i] || `Level ${i + 1}`;
        lines.push(`| ${label} | \`${s.length > 80 ? s.slice(0, 80) + '…' : s}\` |`);
      });
      lines.push('');
      lines.push('```css');
      d.shadows.slice(0, 6).forEach((s, i) => lines.push(`/* shadow-${i+1} */ box-shadow: ${s};`));
      lines.push('```');
      lines.push('');
    }
  }

  // ── 8. Animations & Motion ──────────────────────────────────────────────────
  const anim = d.animations || {};
  const hasAnim = anim.transitions?.length || anim.animations?.length || anim.keyframes?.length || anim.libraries?.length;
  if (hasAnim) {
    lines.push('## Animations & Motion');
    lines.push('');

    if (anim.libraries?.length > 0) {
      lines.push('### Animation Technologies Detected');
      anim.libraries.forEach(lib => lines.push(`- ${lib}`));
      lines.push('');
    }

    if (anim.transitions?.length > 0) {
      lines.push('### Transition Patterns');
      lines.push('```css');
      anim.transitions.slice(0, 6).forEach((t, i) => lines.push(`/* transition-${i+1} */ transition: ${t};`));
      lines.push('```');
      lines.push('');
    }

    if (anim.animations?.length > 0) {
      lines.push('### Active Animations (CSS)');
      lines.push('```css');
      anim.animations.slice(0, 4).forEach((a, i) => lines.push(`/* animation-${i+1} */ animation: ${a};`));
      lines.push('```');
      lines.push('');
    }

    if (anim.keyframes?.length > 0) {
      lines.push('### Keyframe Names Detected');
      lines.push(anim.keyframes.join(', '));
      lines.push('');
    }

    // Extract default duration and easing from first transition
    if (anim.transitions?.length > 0) {
      const first = anim.transitions[0];
      const durationMatch = first.match(/(\d+\.?\d*m?s)/);
      const easingMatch = first.match(/(ease[-\w]*|linear|cubic-bezier[^,)]+\))/);
      if (durationMatch || easingMatch) {
        lines.push('### Motion Principles');
        if (durationMatch) lines.push(`- Default duration: ${durationMatch[1]}`);
        if (easingMatch)   lines.push(`- Default easing: ${easingMatch[1]}`);
        lines.push(`- Reduced motion: Use \`@media (prefers-reduced-motion: reduce)\` to disable animations`);
        lines.push('');
      }
    }
  }

  // ── Interaction States ───────────────────────────────────────────────────────
  const iStates = d.interactionStates || {};
  const hoverEntries = Object.entries(iStates.hover || {}).slice(0, 6);
  const focusEntries = Object.entries(iStates.focus || {}).slice(0, 4);

  if (hoverEntries.length > 0 || focusEntries.length > 0) {
    lines.push('## Interaction States');
    lines.push('');

    if (hoverEntries.length > 0) {
      lines.push('### Hover');
      lines.push('```css');
      hoverEntries.forEach(([sel, changes]) => {
        if (!sel) return;
        lines.push(`${sel}:hover {`);
        Object.entries(changes).forEach(([prop, val]) => lines.push(`  ${prop}: ${val};`));
        lines.push('}');
      });
      lines.push('```');
      lines.push('');
    }

    if (focusEntries.length > 0) {
      lines.push('### Focus');
      lines.push('```css');
      focusEntries.forEach(([sel, changes]) => {
        if (!sel) return;
        lines.push(`${sel}:focus {`);
        Object.entries(changes).forEach(([prop, val]) => lines.push(`  ${prop}: ${val};`));
        lines.push('}');
      });
      lines.push('```');
      lines.push('');
    }
  }

  // ── Decorative details ──────────────────────────────────────────────────────
  const deco = d.decorative || {};
  const scrollbar = deco.scrollbar || {};
  const hasScrollbar = scrollbar.width || scrollbar.thumbColor;
  const hasSelection = deco.selection;

  if (hasScrollbar || hasSelection) {
    lines.push('## Decorative Details');
    lines.push('');

    if (hasScrollbar) {
      lines.push('### Custom Scrollbar');
      lines.push('```css');
      if (scrollbar.width)       lines.push(`::-webkit-scrollbar { width: ${scrollbar.width}; }`);
      if (scrollbar.trackColor)  lines.push(`::-webkit-scrollbar-track { background: ${scrollbar.trackColor}; }`);
      if (scrollbar.thumbColor)  lines.push(`::-webkit-scrollbar-thumb { background: ${scrollbar.thumbColor}; border-radius: ${scrollbar.thumbRadius || '4px'}; }`);
      lines.push('```');
      lines.push('');
    }

    if (hasSelection) {
      lines.push('### Selection Color');
      lines.push('```css');
      lines.push(`::selection {`);
      if (deco.selection.background) lines.push(`  background: ${deco.selection.background};`);
      if (deco.selection.color)      lines.push(`  color: ${deco.selection.color};`);
      lines.push(`}`);
      lines.push('```');
      lines.push('');
    }
  }

  // ── Z-Index Scale ────────────────────────────────────────────────────────────
  if (d.zIndex?.length > 0) {
    lines.push('## Z-Index Scale');
    lines.push('');
    lines.push('Detected values: ' + d.zIndex.join(' · '));
    lines.push('');
  }

  // ── Icon System ─────────────────────────────────────────────────────────────
  if (d.icons?.libraries?.length > 0) {
    lines.push('## Icon System');
    lines.push('');
    lines.push(`- Library: ${d.icons.libraries.join(', ')}`);
    if (d.icons.defaultSize) lines.push(`- Default size: ${d.icons.defaultSize}`);
    lines.push('');
  }

  // ── Design Rules ─────────────────────────────────────────────────────────────
  lines.push('## Design Rules');
  lines.push('');
  lines.push('These rules are derived from the extracted design system. Follow them exactly.');
  lines.push('');

  // Typography rules
  lines.push('### Typography');
  {
    const typoRules = buildTypographyRules(d);
    typoRules.forEach(r => lines.push(`- ${r}`));
  }
  lines.push('');

  // Spacing rules
  lines.push('### Spacing');
  {
    const scaleVals = (d.spacing?.values || []).filter(v => v.endsWith('px')).slice(0, 8).join(', ');
    if (scaleVals) lines.push(`- Use **only** these spacing values: ${scaleVals}`);
    lines.push(`- Base unit: ${d.spacing?.baseUnit || '8px'} — always multiply by integers`);
    lines.push('- Never use magic numbers (e.g. 13px, 17px) — round to nearest scale value');
    lines.push('- Consistent padding within same component type — never mix scales');
  }
  lines.push('');

  // Component rules
  lines.push('### Components');
  {
    const compRules = buildComponentRules(d);
    compRules.forEach(r => lines.push(`- ${r}`));
  }
  lines.push('');

  // ── 9. Do's and Don'ts ──────────────────────────────────────────────────────
  lines.push('## Do\'s and Don\'ts');
  lines.push('');
  lines.push('### DO');

  const dos = buildDos(d);
  dos.forEach(item => lines.push(`- ${item}`));
  lines.push('');
  lines.push("### DON'T");

  const donts = buildDonts(d);
  donts.forEach(item => lines.push(`- ${item}`));
  lines.push('');

  // ── Responsive Behavior ──────────────────────────────────────────────────────
  if (d.breakpoints?.length > 0) {
    lines.push('## Responsive Behavior');
    lines.push('');
    const bps = d.breakpoints;
    lines.push(`- Mobile (< ${bps[0]}): single column layout, full-width CTAs`);
    if (bps.length > 1) lines.push(`- Tablet (${bps[0]} – ${bps[Math.floor(bps.length/2)]}): 2-column max`);
    lines.push(`- Desktop (> ${bps[Math.floor(bps.length/2)] || '1024px'}): multi-column, full navigation`);
    lines.push('');
  }

  // ── Agent Prompt Guide ───────────────────────────────────────────────────────
  lines.push('## Agent Prompt Guide');
  lines.push('');
  lines.push('Always reference this file before generating or modifying any UI component.');
  lines.push('');

  // Quick Color Reference table
  const colorRef = [];
  if (roles.backgrounds?.[0])  colorRef.push({ token: 'Page background', value: roles.backgrounds[0].value, use: 'Body, page background' });
  if (roles.surfaces?.[0])     colorRef.push({ token: 'Surface', value: roles.surfaces[0].value, use: 'Cards, panels' });
  if (roles.text?.[0])         colorRef.push({ token: 'Primary text', value: roles.text[0].value, use: 'All body text, headings' });
  if (roles.accents?.[0])      colorRef.push({ token: 'Accent / CTA', value: roles.accents[0].value, use: 'Primary CTAs, links, brand' });
  if (roles.semantic?.error)   colorRef.push({ token: 'Error', value: roles.semantic.error, use: 'Error states, destructive actions' });
  if (roles.semantic?.success) colorRef.push({ token: 'Success', value: roles.semantic.success, use: 'Success states, confirmations' });
  if (roles.semantic?.warning) colorRef.push({ token: 'Warning', value: roles.semantic.warning, use: 'Warning states' });

  if (colorRef.length > 0) {
    lines.push('### Quick Color Reference');
    lines.push('');
    lines.push('| Token | Value | Use |');
    lines.push('|-------|-------|-----|');
    colorRef.forEach(({ token, value, use }) => lines.push(`| ${token} | \`${value}\` | ${use} |`));
    lines.push('');
  }

  lines.push('### Rules');
  lines.push('');
  lines.push('- Use **only** colors from "Color Palette & Roles" — never invent values');
  {
    const primaryFont = d.typography?.h1?.fontFamily?.split(',')[0].replace(/['"]/g, '').trim() || d.fonts?.detected?.[0];
    if (primaryFont) lines.push(`- Use **only** \`${primaryFont}\` for display/heading text — never substitute`);
  }
  lines.push('- Apply spacing from the defined scale — maintain the base grid unit');
  lines.push('- Match all component states: hover, focus, active, disabled');
  if (d.animations?.transitions?.length > 0) {
    lines.push('- Replicate transition patterns — match duration and easing');
  }
  if (d.icons?.libraries?.length > 0) {
    lines.push(`- Use ${d.icons.libraries[0]} icon library at consistent sizes`);
  }
  lines.push('- Respect `prefers-reduced-motion` for all animations');
  lines.push('- When in doubt about any value not listed — ask, do not guess');
  lines.push('');

  // Quality checklist
  lines.push('### Quality Checklist');
  lines.push('');
  lines.push('Before submitting any UI component, verify:');
  lines.push('');
  lines.push('- [ ] All colors from defined palette — no invented values');
  lines.push('- [ ] All spacing from defined scale — no magic numbers');
  lines.push(`- [ ] Font: ${(d.typography?.h1?.fontFamily?.split(',')[0].replace(/['"]/g, '').trim() || d.fonts?.detected?.[0] || 'correct font')} used — no substitutes`);
  lines.push('- [ ] Hover state defined for every interactive element');
  lines.push('- [ ] Focus state defined (keyboard navigation)');
  lines.push('- [ ] Disabled state considered');
  if (d.breakpoints?.length > 0) {
    lines.push(`- [ ] Mobile layout tested (< ${d.breakpoints[0]})`);
  }
  if (d.animations?.transitions?.length > 0) {
    lines.push('- [ ] `prefers-reduced-motion` handled for animations');
  }
  lines.push('- [ ] No hardcoded `#000000` or `#ffffff` unless in defined palette');
  lines.push('- [ ] Border radius from defined scale only');
  if (d.shadows?.length > 0) {
    lines.push('- [ ] Shadow from defined elevation levels only');
  }

  return lines.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function buildSpacingScale(pxValues, baseUnit) {
  const base = parseInt(baseUnit) || 8;
  const names = ['xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', '4xl'];
  // Deduplicate and sort
  const unique = [...new Set(pxValues.map(v => parseFloat(v)).filter(v => !isNaN(v)))].sort((a, b) => a - b);
  return unique.slice(0, 8).map((val, i) => ({
    name: names[i] || `${i+1}x`,
    value: `${val}px`
  }));
}

function buildDos(d) {
  const dos = [];
  const comp = d.components || {};
  const theme = d.theme || {};

  if (comp.card?.sample?.border && !comp.card.sample.boxShadow) {
    dos.push('Use 1px borders on cards (no drop shadows)');
  } else if (comp.card?.sample?.boxShadow) {
    dos.push('Use box shadows for card elevation');
  }
  if (d.fonts?.detected?.length > 0) {
    dos.push(`Use ${d.fonts.detected[0]} for all UI text`);
  }
  if (d.spacing?.baseUnit) {
    dos.push(`Maintain ${d.spacing.baseUnit} grid alignment`);
  }
  if (d.animations?.transitions?.length > 0) {
    dos.push('Apply smooth transitions on interactive elements');
  }
  if (theme.isDark) {
    dos.push('Keep the dark background — do not switch to white surfaces');
  }
  if (d.borderRadius?.length > 0) {
    dos.push(`Use border-radius values from the defined scale (${d.borderRadius.slice(0,3).join(', ')})`);
  }
  dos.push('Use semantic color names from the token system');
  dos.push('Match hover/focus states to existing component patterns');
  return dos;
}

function buildDonts(d) {
  const donts = [];
  const theme = d.theme || {};
  const comp = d.components || {};

  donts.push('Never use colors outside the defined palette');
  if (d.fonts?.detected?.length > 0) {
    donts.push(`Never substitute ${d.fonts.detected[0]} with system fonts`);
  }
  if (theme.isMinimal && d.shadows?.length < 3) {
    donts.push('Don\'t add heavy drop shadows — this is a minimal/flat design');
  }
  donts.push('Don\'t use font sizes outside the defined type scale');
  donts.push('Don\'t use arbitrary z-index values — stick to the z-index scale');
  if (!theme.hasGradients) {
    donts.push('Don\'t add gradient fills — the design uses flat colors');
  }
  donts.push('Don\'t disable focus styles — they\'re required for accessibility');
  return donts;
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ── Color contrast helpers ────────────────────────────────────────────────────

function hexLuminance(hex) {
  if (!hex || !hex.startsWith('#') || hex.length < 7) return 0.5;
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const toLinear = c => c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  return 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
}

function contrastRatio(hex1, hex2) {
  const l1 = hexLuminance(hex1);
  const l2 = hexLuminance(hex2);
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return Math.round(((lighter + 0.05) / (darker + 0.05)) * 10) / 10;
}

function wcagRating(ratio) {
  if (ratio >= 7) return 'AAA ✓';
  if (ratio >= 4.5) return 'AA ✓';
  if (ratio >= 3) return 'AA Large ✓';
  return 'Fail ✗';
}

function buildColorPairs(d) {
  const roles = d.colorRoles || {};
  const pairs = [];
  const seen = new Set();

  const bgs = [...(roles.backgrounds || []), ...(roles.surfaces || [])].slice(0, 4);
  const texts = [...(roles.text || [])].slice(0, 3);
  const accents = [...(roles.accents || [])].slice(0, 2);

  const candidates = [...texts, ...accents];

  bgs.forEach(bg => {
    if (!bg.value?.startsWith('#')) return;
    candidates.forEach(text => {
      if (!text.value?.startsWith('#')) return;
      const key = `${bg.value}|${text.value}`;
      if (seen.has(key)) return;
      seen.add(key);
      const ratio = contrastRatio(bg.value, text.value);
      if (ratio < 2) return; // skip near-identical pairs
      pairs.push({ bg: bg.value, text: text.value, ratio, rating: wcagRating(ratio) });
    });
  });

  // Also check most frequent colors against each other
  const topColors = (d.colors || []).slice(0, 8).map(c => c.color);
  for (let i = 0; i < topColors.length; i++) {
    for (let j = i + 1; j < topColors.length; j++) {
      const key = `${topColors[i]}|${topColors[j]}`;
      if (seen.has(key) || pairs.length >= 8) continue;
      seen.add(key);
      const ratio = contrastRatio(topColors[i], topColors[j]);
      if (ratio >= 4.5) {
        pairs.push({ bg: topColors[i], text: topColors[j], ratio, rating: wcagRating(ratio) });
      }
    }
  }

  return pairs.sort((a, b) => b.ratio - a.ratio).slice(0, 6);
}

function buildColorRules(d) {
  const rules = [];
  const roles = d.colorRoles || {};
  const theme = d.theme || {};

  if (roles.accents?.length > 0) {
    const accent = roles.accents[0].value;
    rules.push(`Accent \`${accent}\` — use for primary CTAs and brand moments only, never for body text`);
  }
  if (roles.text?.length > 0) {
    const text = roles.text[0].value;
    rules.push(`Primary text \`${text}\` — default for all body copy and headings`);
    if (roles.text.length > 1) {
      rules.push(`Muted text — use alpha variant of primary text, not a separate grey`);
    }
  }
  if (roles.semantic?.error) {
    rules.push(`Error \`${roles.semantic.error}\` — destructive actions and validation errors only`);
  }
  if (roles.semantic?.success) {
    rules.push(`Success \`${roles.semantic.success}\` — confirmation states only`);
  }
  if (theme.isDark) {
    rules.push('Dark theme — never introduce white or light backgrounds without explicit design approval');
  }
  rules.push('Never invent a color not in this palette — use opacity/alpha of existing colors instead');

  return rules;
}

// ── Typography rules ─────────────────────────────────────────────────────────

function buildTypographyRules(d) {
  const rules = [];
  const typo = d.typography || {};
  const fonts = d.fonts || {};

  const h1Font = typo.h1?.fontFamily?.split(',')[0].replace(/['"]/g, '').trim();
  const bodyFont = typo.p?.fontFamily?.split(',')[0].replace(/['"]/g, '').trim();
  const codeFont = typo.code?.fontFamily?.split(',')[0].replace(/['"]/g, '').trim() || fonts.mono?.[0];

  if (h1Font) rules.push(`Headings: \`${h1Font}\` — never substitute with system fonts`);
  if (bodyFont && bodyFont !== h1Font) rules.push(`Body text: \`${bodyFont}\``);
  if (codeFont) rules.push(`Code/mono: \`${codeFont}\` — for all technical content`);

  // Sizes
  const sizes = Object.entries(typo)
    .filter(([k]) => !k.startsWith('_'))
    .map(([, v]) => parseFloat(v.fontSize))
    .filter(Boolean)
    .sort((a, b) => a - b);
  const uniqueSizes = [...new Set(sizes)];
  if (uniqueSizes.length > 0) {
    rules.push(`Font sizes — use only: ${uniqueSizes.map(s => `${s}px`).join(', ')}`);
  }

  rules.push('Never use more than 3 distinct font sizes within a single UI section');
  rules.push('Establish hierarchy through size and weight — not color alone');
  rules.push('Never bold body text for emphasis — use size increase or color change instead');

  const h1LS = typo.h1?.letterSpacing;
  if (h1LS && h1LS !== '—' && h1LS !== '0px') {
    rules.push(`Display headings require letter-spacing: \`${h1LS}\` — do not omit`);
  }

  return rules;
}

// ── Component rules ───────────────────────────────────────────────────────────

function buildComponentRules(d) {
  const rules = [];
  const comp = d.components || {};
  const variants = d.buttonVariants || [];
  const theme = d.theme || {};

  // Button rules
  if (variants.length > 0 || comp.button) {
    const primary = variants[0] || comp.button?.sample;
    if (primary) {
      rules.push(`Primary button: \`${primary.backgroundColor}\` background, \`${primary.color}\` text, \`${primary.borderRadius}\` radius — do not invert`);
    }
    rules.push('Every button must have a visible hover state — color shift or shadow change');
    rules.push('Every interactive element must have a focus-visible outline for keyboard navigation');
  }

  // Card rules
  if (comp.card?.sample) {
    const card = comp.card.sample;
    const hasShadow = !!card.boxShadow;
    const hasBorder = card.border && card.border !== 'none';
    if (hasShadow && !hasBorder) rules.push('Cards use shadow for elevation — no additional border needed');
    if (hasBorder && !hasShadow) rules.push('Cards use border — no drop shadow unless hovering');
    if (card.borderRadius) rules.push(`Card border-radius: \`${card.borderRadius}\` — consistent across all card variants`);
  }

  // Input rules
  if (comp.input?.sample) {
    rules.push('Form inputs must show clear focus state (border color change or outline)');
    rules.push('Never remove default browser focus ring without providing a custom replacement');
  }

  // Radius rules
  if (d.borderRadius?.length > 0) {
    rules.push(`Border radius — use only: ${d.borderRadius.slice(0, 5).join(', ')}`);
  }

  // Shadow rules
  if (d.shadows?.length > 0) {
    rules.push(`Use only defined shadow levels — never invent new box-shadow values`);
  }

  // Minimal/flat
  if (theme.isMinimal) {
    rules.push('Flat design — avoid adding decorative shadows or heavy borders not in the system');
  }

  return rules;
}
